create table
  public.global_inventory (
    id bigint generated by default as identity not null,
    gold integer null default 0,
    red_ml integer null default 0,
    green_ml integer null default 0,
    blue_ml integer null default 0,
    dark_ml integer null default 0,
    constraint test_global_inventory_pkey primary key (id)
  ) tablespace pg_default;

  create table
  public.potion_inventory (
    id bigint generated by default as identity not null,
    quantity integer null default 0,
    sku text null default ''::text,
    constraint potion_inventory_pkey1 primary key (id)
  ) tablespace pg_default;

  create table
  public.potion_types (
    id bigint generated by default as identity not null,
    red_ml smallint null default '0'::smallint,
    green_ml smallint null default '0'::smallint,
    blue_ml smallint null default '0'::smallint,
    dark_ml smallint null default '0'::smallint,
    price integer null default 0,
    potion_sku text null default 'NULL_POTION'::text,
    potion_name text null default 'Potion'::text,
    constraint potion_inventory_pkey primary key (id)
  ) tablespace pg_default;

  create table
  public.carts_log (
    id bigint generated by default as identity not null,
    customer_name text null default ''::text,
    character_class text null default ''::text,
    level integer null default 0,
    constraint carts_log_pkey primary key (id)
  ) tablespace pg_default;

  create table
  public.cart_items (
    id bigint generated by default as identity not null,
    cart_id integer null,
    item_sku text null,
    quantity integer null default 0,
    constraint cart_items_pkey primary key (id)
  ) tablespace pg_default;

  create table
  public.capacity (
    id bigint generated by default as identity not null,
    ml_capacity integer null default 1,
    potion_capacity integer null default 1,
    constraint capacity_pkey primary key (id)
  ) tablespace pg_default;