create table
  public.capacity (
    id bigint generated by default as identity not null,
    ml_capacity integer null default 1,
    potion_capacity integer null default 1,
    constraint capacity_pkey primary key (id)
  ) tablespace pg_default;

create table
  public.carts_log (
    id bigint generated by default as identity not null,
    customer_name text null default ''::text,
    character_class text null default ''::text,
    level integer null default 0,
    day text null,
    hour smallint null,
    timestamp timestamp with time zone null default now(),
    constraint carts_log_pkey primary key (id)
  ) tablespace pg_default;

create table
  public.cart_items (
    id bigint generated by default as identity not null,
    cart_id integer not null,
    item_sku text not null,
    quantity integer not null default 0,
    constraint cart_items_pkey primary key (id),
    constraint cart_items_cart_id_fkey foreign key (cart_id) references carts_log (id) on update cascade on delete cascade
  ) tablespace pg_default;

create table
  public.date_time (
    id bigint generated by default as identity not null,
    day text null,
    hour smallint null,
    constraint date_time_pkey primary key (id)
  ) tablespace pg_default;

create table
  public.global_inventory (
    id bigint generated by default as identity not null,
    gold integer null default 0,
    red_ml integer null default 0,
    green_ml integer null default 0,
    blue_ml integer null default 0,
    dark_ml integer null default 0,
    "orderID" integer null,
    constraint test_global_inventory_pkey primary key (id)
    constraint global_inventory_orderID_key unique (orderID)
  ) tablespace pg_default;

create table
  public.potion_types (
    id bigint generated by default as identity not null,
    red_ml smallint not null default '0'::smallint,
    green_ml smallint not null default '0'::smallint,
    blue_ml smallint not null default '0'::smallint,
    dark_ml smallint not null default '0'::smallint,
    price integer not null default 0,
    potion_sku text not null default 'NULL_POTION'::text,
    potion_name text not null default 'Potion'::text,
    constraint potion_inventory_pkey primary key (id)
    constraint potion_types_potion_sku_key unique (potion_sku)
  ) tablespace pg_default;

create table
  public.potion_inventory (
    id bigint generated by default as identity not null,
    quantity integer not null default 0,
    sku text not null,
    constraint potion_inventory_pkey1 primary key (id)
  ) tablespace pg_default;

create table
  public.visits (
    id bigint generated by default as identity not null,
    visit_id integer null,
    class text null,
    lvl_avg real null,
    num integer null,
    constraint visits_pkey primary key (id)
  ) tablespace pg_default;